version: "3.9"

services:
  database:
    image: postgres:13.2
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  backend:
    image: wallet-wingman-backend:latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    depends_on:
      - database
    command: npm run dev

  frontend:
    image: wallet-wingman-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app/react-app
      - /app/react-app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development

volumes:
  db_data:

